image: "fvanhems/dx:compcert3.17-4.14"
test:
  stage: test

  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
  script:
    - opam pin .
    - ./configure
    - make test
